name: Run Selenium Tests Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *"  # Запуск кожні 30 хвилин
  workflow_dispatch:  # Додаємо можливість запуску вручну

jobs:
  selenium-tests:
    runs-on: windows-latest  # Вибір Windows-образу
    steps:
      - name: Set environment to UTF-8
        run: |
          $env:PYTHONIOENCODING="utf-8"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          choco install python
          pip install selenium
          choco install chromedriver
          pip install telebot
      - name: Run Selenium Tests
        run: python main.py
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git stash push --include-untracked || echo "No changes to stash"
          git pull --rebase
          git stash pop || echo "No changes to pop"
          git add .
          git commit -m "Update file with Selenium script" || echo "No changes to commit"
          git push
